### ISSUE TITLE
Example 2 in Jupyter tutorial does not compile

### ISSUE THREAD

**Issue by dangeles** [rsnemmen/BCES#2]
Multiple minor bugs, but even when the minor bugs are solved, bces.bcesp() returns an error

Traceback error:

"""
Traceback (most recent call last):
  File "/Users/dangeles/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/dangeles/anaconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/dangeles/my_repos/BCES/bces.py", line 224, in ab
    for i in range(nsim):
TypeError: 'float' object cannot be interpreted as an integer
"""

**Comment by rsnemmen** [comment]
Dear David,

I will check it out and get back to you soon.

Best,
Rodrigo

**Comment by rsnemmen** [comment]
Bug is fixed. Could you pull in the latest changes and check it again to see if this solved your problem?
