### ISSUE TITLE
line 249 UnboundLocalError: local variable 'am' referenced before assignment

### ISSUE THREAD

**Issue by yahiaashraf222** [rsnemmen/BCES#9]
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/esraa/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/esraa/anaconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/esraa/anaconda3/lib/python3.9/site-packages/bces-1.3.1-py3.9.egg/bces/bces.py", line 249, in ab
    return am,bm
UnboundLocalError: local variable 'am' referenced before assignment
"""

NOTE: i have tried to assign them as empty variables or arrays then it gave me other error "TypeError: array() missing required argument 'object' (pos 0)"

**Comment by rsnemmen** [comment]
Fixed!
